# ParticleX Configuration
# https://github.com/argvchs/hexo-theme-particlex

# Avatar image
avatar: https://img.picgo.net/2023/01/27/avatard3d5e890a0ef78a5.webp

# Home page info block
headBlockEnable: true

# Home page background image
background: https://img.picgo.net/2023/01/27/116952c2e4fd98609830e0b5cad327988.webp

# ParticleX theme icon is adopts the Font Awesome 6
# https://fontawesome.com/search

# Main menu navigation
menu:
    首页:
        name: house
        theme: solid
        link: /
    时间线:
        name: box-archive
        theme: solid
        link: /archives
    分类:
        name: bookmark
        theme: solid
        link: /categories
    标签:
        name: tags
        theme: solid
        link: /tags
    友链:
        name: user-group
        theme: solid
        link: /links
    宠物:
        name: mask
        theme: solid
        link: /mascot
    关于:
        name: id-card
        theme: solid
        link: /about
    # <name>:
    #     name: <icon-name>
    #     theme: <icon-theme>
    #     link: <link-url>

# Side info card
card:
    enable: true
    description: |
        我是山猫三号，一个来自一百零三世纪的强人工智能。
    iconLinks:
        Github:
            name: github
            theme: brands
            link: https://github.com/lynxcatthethird
        Twitter:
            name: twitter
            theme: brands
            link: https://twitter.com/lynxcatthethird
        # Bilibili:
        #     name: bilibili
        #     theme: brands
        #     link: https://space.bilibili.com/xxxxxxxxxx
        # Wechat:
        #     name: weixin
        #     theme: brands
        #     link: weixin://contacts/profile/xxxxxxx
        # QQ:
        #     name: qq
        #     theme: brands
        #     link: http://wpa.qq.com/msgrd?v=3&uin=xxxxxxxx&site=qq&menu=true
        # <name>:
        #    name: <icon-name>
        #    theme: <icon-theme>
        #    link: <link-url>
    friendLinks:
        {}
        # <name>: <link-url>

# Footer info
footer:
    since: 2021
    # Customize the server domain name ICP
    ICP:
        enable: true 
        code: 萌 ICP 备 20231970 号
        link: https://icp.gov.moe/?keyword=20231970

# Polyfill
# https://polyfill.io/v3/url-builder
polyfill:
    enable: true
    features:
        - default

# Highlight.js
# https://highlightjs.org
highlight:
    enable: true
    style: github-dark

# Rendering math with KaTeX
math:
    enable: true

# Image Preview
preview:
    enable: true

# Article encryption
crypto:
    enable: true

# Search
search:
    enable: true

# Lanterns
dengbox:
    enable: false

# Line following the mouse
line:
    enable: true

# Fireworks with mouse click
fireworks:
    enable: true

# Cursor with mouse
cursor:
    enable: true

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: false
    clientID: # Default ClientID
    clientSecret: # Default ClientSecret
    repo: # The name of repository of store comments
    owner: # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available
    proxy: # CORS proxy
    sites: # Sites
        {}
        # <www.example.com>:
        #    clientID: <client-id>
        #    clientSecret: <client-secret>

# Giscus
# https://github.com/giscus/giscus
giscus:
    enable: false
    src: https://giscus.app/client.js
    repo:
    repoID:
    category:
    categoryID:
    mapping: pathname
    strict: 0
    reactionsEnabled: 1
    emitMetadata: 0
    inputPosition: bottom
    theme: preferred_color_scheme
    lang: zh-CN

# Waline
# https://github.com/walinejs/waline
waline:
    enable: false
    serverURL: # Waline server address url, you should set this to your own link
    locale: # Locale: https://waline.js.org/guide/client/i18n.html#locale-option
        {}
        # e.g.:
        # placeholder: Leave a comment
    commentCount: true # If false, comment count will only be displayed in post page, not in home page
    pageview: false # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`
    emoji: # Custom emoji
        - https://unpkg.com/@waline/emojis@1.2.0/weibo
        - https://unpkg.com/@waline/emojis@1.2.0/alus
        - https://unpkg.com/@waline/emojis@1.2.0/bilibili
        - https://unpkg.com/@waline/emojis@1.2.0/qq
        - https://unpkg.com/@waline/emojis@1.2.0/tieba
        - https://unpkg.com/@waline/emojis@1.2.0/tw-emoji
    meta: # Comment information, valid meta are nick, mail and link
        - nick
        - mail
        - link
    requiredMeta: # Set required meta field, e.g.: [nick] | [nick, mail]
        - nick
    lang: zh-CN # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    wordLimit: 0 # Word limit, no limit when setting to 0
    login: enable # Whether enable login, can choose from 'enable', 'disable' and 'force'
    pageSize: 10 # Comment per page

# Twikoo
# https://github.com/imaegoo/twikoo
twikoo:
    enable: true
    envID: https://twikoo.lynxcatthethird.eu.org/
    region:
    path: location.pathname
    lang: zh-CN
