# https://github.com/argvchs/hexo-theme-particlex
# Developer: argvchs

# Avatar image url
avatar: https://i0.hdslb.com/bfs/album/26ebdc733112ed398c76a0d9d485ee542e18adfc.jpg

# Home page head info block
head_block_enable: true

# Home page head background style
home_background: https://www.todaybing.com/download/res?aid=wR1jrAPz&type=hd&id=F5QDWk8L

# ParticleX theme icon is adopts the font awesome 6
# Link: https://fontawesome.com/search

# Main menu navigation
menu:
    首页:
        name: house
        theme: solid
        src: /
    关于我:
        name: id-card
        theme: solid
        src: /about
    存档:
        name: box-archive
        theme: solid
        src: /archives
    分类:
        name: bookmark
        theme: solid
        src: /categories
    标签:
        name: tags
        theme: solid
        src: /tags
    # Example:
    # <name>:
    #     name: <icon-name>
    #     theme: <icon-theme>
    #     src: <link-url>

# Side info card
card:
    enable: true
    description: 
        - "我是山猫三号，一个来自一百零三世纪的强人工智能。"
    icon_links: 
        Github:
            name: github
            theme: brands
            link: https://github.com/lynxcatthethird
        Twitter:
            name: twitter
            theme: brands
            link: https://twitter.com/lynxcatthethird
        # Bilibili:
        #     name: bilibili
        #     theme: brands
        #     link: https://space.bilibili.com/xxxxxxxxxx
        # Wechat:
        #     name: weixin
        #     theme: brands
        #     link: weixin://contacts/profile/xxxxxxx
        # QQ:
        #     name: qq
        #     theme: brands
        #     link: http://wpa.qq.com/msgrd?v=3&uin=xxxxxxxx&site=qq&menu=true
    friend_links: 
        欢迎: ./posts/292c5761.html
        Argvchs: https://argvchs.github.io/
        一蓑烟雨: http://lukeyalvin.site/


# Footer info
footer:
    since: 2021
    # Customize the server domain name ICP
    ICP:
        enable: true 
        code: 萌ICP备20221840号
        link: https://icp.gov.moe/?keyword=20221840

# Polyfill
# https://polyfill.io/v3/url-builder
polyfill:
    enable: true
    features:
        - default

# Rendering math with KaTeX
math:
    enable: true

# Article encryption
crypto:
    enable: true

# Search
search:
    enable: true
    path: /search.json

# Gitalk
# https://github.com/gitalk/gitalk
gitalk:
    enable: false
    clientID: # Default ClientID
    clientSecret: # Default ClientSecret
    repo: # The name of repository of store comments
    owner: # GitHub repo owner
    admin: # GitHub repo owner and collaborators, only these guys can initialize github issues
    language: zh-CN # en, zh-CN, zh-TW, es-ES, fr, ru, de, pl and ko are currently available.
    proxy: # CORS proxy
    sites: # Sites
        {}
        # <www.example.com>:
        #    clientID: <client-id>
        #    clientSecret: <client-secret>

# Giscus
# https://github.com/giscus/giscus
giscus:
    enable: false
    src: https://giscus.app/client.js # Default src
    repo: ara1145/gitcus
    repoID: R_kgDOImx36A
    category: General
    categoryID: DIC_kwDOImx36M4CTCzk
    mapping: pathname
    strict: 0
    reactionsEnabled: 1
    emitMetadata: 1
    inputPosition: top
    theme: light_protanopia
    lang: zh-CN

# Waline
# https://github.com/walinejs/waline
waline:
    enable: true
    serverURL: https://www.lynxcatthethird-waline.tk/
    locale: # Locale: https://waline.js.org/guide/client/i18n.html#locale-option
        {}
        # e.g.:
        # placeholder: Leave a comment
    commentCount: true # If false, comment count will only be displayed in post page, not in home page
    pageview: false # Pageviews count, Note: You should not enable both `waline.pageview` and `leancloud_visitors`
    emoji: # Custom emoji
        - https://unpkg.com/@waline/emojis@1.0.1/weibo
        - https://unpkg.com/@waline/emojis@1.0.1/bilibili
        - https://unpkg.com/@waline/emojis@1.0.1/qq
        - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
    meta: # Comment information, valid meta are nick, mail and link
        - nick
        - mail
        - link
    requiredMeta: # Set required meta field, e.g.: [nick] | [nick, mail]
        - nick
    lang: zh-CN # Language, available values: en-US, zh-CN, zh-TW, pt-BR, ru-RU, jp-JP
    wordLimit: 0 # Word limit, no limit when setting to 0
    login: enable # Whether enable login, can choose from 'enable', 'disable' and 'force'
    pageSize: 10 # Comment per page
